services:
  classic-fuzzer:
    build: .
    container_name: classic-fuzzer
    networks:
      - fuzzer-network
    volumes:
      - ./fume_sync:/app/fume_sync
    restart: unless-stopped

networks:
  fuzzer-network:
    driver: bridge
